### ISSUE TITLE
jekyll-sitemap.rb:34:in `block in html_files': undefined method `extname' for #<Jekyll:Page @name="index.html"> (NoMethodError)

### ISSUE THREAD

**Issue by bezhermoso** [jekyll/jekyll-sitemap#101]
I am getting this error during `jekyll serve`:

```
jekyll-sitemap.rb:34:in `block in html_files': undefined method `extname' for #<Jekyll:Page @name="index.html"> (NoMethodError)
```

I am using v0.10.0 on a Jekyll 2.5.3 site.

**Comment by parkr** [comment]
@bezhermoso Unfortunately the latest version doesn't seem compatible with Jekyll 2, only Jekyll 3. @pathawks/@benbalter, is this documented? We should bump in the gemspec!

**Comment by bezhermoso** [comment]
@parkr Ah gotcha. Didn't seem to be the case since `bundle install` didn't complain. What's the latest version that supports Jekyll 2.x?

**Comment by bezhermoso** [comment]
@parkr Just updated our site to Jekyll 3.0 and followed the migration guide. I'm still getting the same error.

**Comment by pathawks** [comment]
Line 34 was last modified in #93 which passes tests with Jekyll 2.x

Could there be something else going on here?

**Comment by pathawks** [comment]
Currently, [all tests are passing with Jekyll 2.5.3](https://travis-ci.org/jekyll/jekyll-sitemap/jobs/113326999#L178) and the current **master** of **jekyll-sitemap**.

We are still [actively testing against Jekyll 2.5](https://github.com/jekyll/jekyll-sitemap/blob/1327e2df64ad3e7177ebb70f55d8a0466c663c34/.travis.yml#L15-L17) and have not done anything recently to drop support for Jekyll 2.x. If something is broken, we need to fix it.

@bezhermoso Is there any way you could submit a Pull Request with a failing test? Alternatively, is the source of your site public? I could try to monkey around with it a bit to see where things are breaking.

**Comment by bezhermoso** [comment]
@pathawks Noted.

Unfortunately the source is not open to public. However I'll spend some time creating a failing test (and perhaps a proposed fix.)

**Comment by pathawks** [comment]
> However I'll spend some time creating a failing test (and perhaps a proposed fix.)

Awesome! Thanks :+1:

**Comment by bezhermoso** [comment]
Hi everyone!

It's been a while since I looked into this again, but I finally found the culprit in my case: there was a generator that is adding `Jekyll::Page` instances to `site.static_files`. So I don't think its a bug on `jekyll-sitemap` per se.

**Comment by parkr** [comment]
@bezhermoso Glad to hear you got it sorted! Thanks for reporting back.
