### ISSUE TITLE
Exclude a hidden folder from sitemap

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-sitemap#102]
Hi there,

I have a hidden folder `node-v4.1.0-darwin-x64` in my site directory. And when the sitemap is generated it includes `html` files from this folder. Is there any way to exclude a whole folder from the sitemap?

**Comment by benbalter** [comment]
@iloveip when you say "hidden folder", do you mean one that you'd like in the site output, but not listed in the sitemap? If so, can you explain a bit more about your use case?

**Comment by iloveip** [comment]
@benbalter Thank you very much for your reply!

I guess this folder was installed by some of the plugins. I just removed and nothing happened :) The site is working ok. So it's not a problem anymore. Sorry for the trouble!
