### ISSUE TITLE
Exclude certain html files from sitemap 

### ISSUE THREAD

**Issue by robinj** [jekyll/jekyll-sitemap#103]
I have no solution for this, so I am leaving this is a feature request for now so that someone/I can pick it up when they have time. 

There are some instances where you may want to have an html file in a specific part of your site but you may not want it to be in the sitemap. 

An example of this is the Google Webmaster Tools verification file which consists google followed of a number of random hex digits with the html extension. I am sure there are other instances where one may need a file for verification purposes too.

**Comment by xHN35RQ** [comment]
Placing this at the top of a page works great for me!

```
---
sitemap: false
---
```

**Comment by robinj** [comment]
True. It feels a little strange to put that at the top of an html page as it's not really valid markup but fair enough. I will close this issue

**Comment by xHN35RQ** [comment]
Jekyll removes the two triple-dashes and everything in between at build time.
