### ISSUE TITLE
URL encoded permalinks in posts cause incorrect sitemap

### ISSUE THREAD

**Issue by ripples-alive** [jekyll/jekyll-sitemap#105]
I migrated my blog from WordPress to Jekyll.
Posts exported from WordPress have URL encoded permalinks. I don't know whether the permalink should be encoded in post, but it does work well except sitemap. The generated sitemap will have the encoded URL encoded again.
Whether it's possible to solve this problem without updating all permalinks in posts?

**Comment by pathawks** [comment]
Can you provide an example please?

I think this and #106 are related.

**Comment by ripples-alive** [comment]
*Seems something wrong with my email notification, I just saw it this morning.*
As for #106 , it seems that it's nearly the same as my problem.

As for example, my post head:

```
title: Nginx SSL证书折腾记
permalink: /nginx-ssl%e8%af%81%e4%b9%a6%e6%8a%98%e8%85%be%e8%ae%b0/
```

The correct url is `/nginx-ssl%e8%af%81%e4%b9%a6%e6%8a%98%e8%85%be%e8%ae%b0/`, but I get `/nginx-ssl%25e8%25af%2581%25e4%25b9%25a6%25e6%258a%2598%25e8%2585%25be%25e8%25ae%25b0/` in sitemap.

Now, I update permalink in my post to deal with this issue:

```
title: Nginx SSL证书折腾记
permalink: /nginx-ssl证书折腾记/
```

Then, the generated sitemap is correct now.

**Comment by pathawks** [comment]
Ok, I am going to close this, and track this issue on #106.

We will figure this out :+1:
