### ISSUE TITLE
Some URLs are escaped twice in sitemap

### ISSUE THREAD

**Issue by kimiazhu** [jekyll/jekyll-sitemap#106]
for the Chinese post title, the generated url will be encoded twice in jekyll-sitemap, cause it can not be open correctly. please fix it.

**Comment by pathawks** [comment]
Do you have an example?
How can I reproduce this?

**Comment by kimiazhu** [comment]
yeah, thank you.

you can reproduce it.

I used jekyll in github pages.

- what in my _config.xml:
gems: 
  - jekyll-paginate
  - jekyll-sitemap

- what in my post's title (example):
layout:     post
title:      "Go语言传值和深浅复制问题" 

the title contain some Chinese characters, then, it will generate the following url in sitemap.xml:

http://kchu.me/2016/03/27/Go%25E8%25AF%25AD%25E8%25A8%2580%25E4%25BC%25A0%25E5%2580%25BC%25E5%2592%258C%25E6%25B7%25B1%25E6%25B5%2585%25E5%25A4%258D%25E5%2588%25B6%25E9%2597%25AE%25E9%25A2%2598/

it's not correct, the right one is:

http://kchu.me/2016/03/27/Go%E8%AF%AD%E8%A8%80%E4%BC%A0%E5%80%BC%E5%92%8C%E6%B7%B1%E6%B5%85%E5%A4%8D%E5%88%B6%E9%97%AE%E9%A2%98/

it do url encode twice.. the second time encode the '%' to %25

**Comment by pathawks** [comment]
It seems that if the permalink is specified explicitly in the front matter then Jekyll will not percent encode it, but if the permalink is specified implicitly in the filename, Jekyll _will_ encode it.

Short of an `escape_once` filter, I am not sure what to do. Either we should always escape permalinks or we should never escape permalinks  ¯\_(ツ)_/¯

**Comment by ripples-alive** [comment]
For temporary fix, maybe you can url decode the url first and then encode it again. I'm not sure whether this is good.

```
url_encode(url_decode('http://kchu.me/2016/03/27/Go%E8%AF%AD%E8%A8%80%E4%BC%A0%E5%80%BC%E5%92%8C%E6%B7%B1%E6%B5%85%E5%A4%8D%E5%88%B6%E9%97%AE%E9%A2%98/'))
url_encode(url_decode('http://kchu.me/2016/03/27/Go语言传值和深浅复制问题/'))
url_encode('http://kchu.me/2016/03/27/Go语言传值和深浅复制问题/')
```

The result for the above three statements are the same.

But unfortunately, if the original url already contains `%xx` pattern, we may get a unexpected result. However, I don't think this situation is common.

**Comment by pathawks** [comment]
The way to solve this is with Addressable. If the permalink is already encoded or not, Addressable will return a valid encoded url.

```ruby
Addressable::URI.parse(url).normalize.to_s
```

I am working on a fix. :+1:

**Comment by kimiazhu** [comment]
@pathawks Thank you! for now I'm using a custom page named `sitemap.xml` to produce the sitemap. I will check it when you fixed. :D

**Comment by pathawks** [comment]
This has been fixed in **master** 🎉 

You can use the patched version today by adding this to your Gemfile:

```ruby
gem 'jekyll-sitemap', :github => 'jekyll/jekyll-sitemap', :branch => 'master'
```
