### ISSUE TITLE
Constatly get the same error - "... you don't have jekyll-sitemap or one of its dependencies installed."

### ISSUE THREAD

**Issue by jonathanphz** [jekyll/jekyll-sitemap#110]
Hi - I'm not sure why and it's probably due to my configuration. I use gulp for jekyll and most times when I come back to a project after a few days I keep getting the same error : "**Dependency Error: Yikes! It looks like you don't have jekyll-sitemap or one of its dependencies installed.**"

To temporarily fix the error I just use "bundle update".  

I get the same error on another project with the same setup. At the moment I use a customized version of https://github.com/shakyShane/jekyll-gulp-sass-browser-sync for jekyll/gulp combination.

Maybe is something simple I'm missing.

Thanks for any help.

The whole error message is: 
`Configuration file: /Users/me/Sites/website/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-sitemap or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-sitemap' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
jekyll 3.1.3 | Error:  jekyll-sitemap
`

**Comment by pathawks** [comment]
When you run Jekyll, do you run `bundle exec jekyll build`?

**Comment by jonathanphz** [comment]
No - the gulp file I use uses jekyll build.

Is that where I messed things up? Should it be bundle exec jekyll build instead?

**Comment by pathawks** [comment]
If you’re using Bundler, yeah, there should be a `bundle exec` in there.

This is one of those gotchas that really irritated me before I got used to it.

**Comment by jonathanphz** [comment]
OK - thanks for the help Pat.

Really appreciate it!

**Comment by pathawks** [comment]
If you modify your Gulp file, does everything work properly? (Looking to close the issue if everything is working properly)

**Comment by jonathanphz** [comment]
it seems to be working, just not sure if it's because I ran the bundle
update command which seemed to fix this temporarily.

But yeah so far it's working fine now.

Thanks
