### ISSUE TITLE
Homepage URL using a trailing slash

### ISSUE THREAD

**Issue by henrywright** [jekyll/jekyll-sitemap#111]
The homepage URL in my generated sitemap.xml seems to be using a trailingslash. Here's an example:

```
<url>
    <loc>https://example.com/</loc>
</url>
```

In _config.yml, I'm setting the url like this:
```
url: https://example.com
```

Should sitemap.xml honour this config setting with reference to my homepage URL?

Please note that pages are listed in sitemap.xml as expected (no trailing slash). For example:

```
<url>
    <loc>https://example.com/about</loc>
</url>
```

**Comment by henrywright** [comment]
Perhaps my homepage should use a trailing slash? When I look at it in the browser address bar, I see:

> https://example.com

Yet when I copy that and paste it into my text editor, I see:

> https://example.com/

That's strange behaviour to me. Does my homepage have a trailing slash or not? It's not just my site where this happens, try copying `https://github.com` from the browser address bar and then paste that into your text editor, you'll get `https://github.com/` (note there's a trailing slash).

**Comment by kleinfreund** [comment]
The trailing slash of a domain’s top level domain (that is the `.com`) represents the directory the document is on the web server. So the difference between `site.com` and `site.com/` is a visual one. Both indicate that the current document is served from the directory where that website lives in.

It does not matter whether in your sitemap there is a `site.com` or `site.com/` entry. What does matter is that there are not both (that would be a duplicate).

**Comment by henrywright** [comment]
Thanks!
