### ISSUE TITLE
No url in <loc> Tag

### ISSUE THREAD

**Issue by GitHub-Mike** [jekyll/jekyll-sitemap#115]
Hello,

I use Jekyll 2.5.3, jekyll-sitemap 0.10.0 under Ruby 1.9.3 .

This is my current sitemap.xml:

    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
    <loc>/</loc>
    </url>
    </urlset>

and they should look:

    <?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        <url>
            <loc>http://www.example.com/</loc>
            <lastmod>2016-05-11</lastmod>
            <changefreq>weekly</changefreq>
        </url>
    </urlset>

This Version is compliant to Google Webmaster Tools!

Is there a possibility to realize this with jekyll-sitemap?

Thanks!

Mike

**Comment by GitHub-Mike** [comment]
I have fixed the problem with "url" option in _config.yml:

    url: www.example.com

Is this (quick & dirty) | the right way ?

Mike

**Comment by xHN35RQ** [comment]
Yes, setting `url` in `_config.yml` sets the `site.url` variable and `jekyll-sitemap` [uses `site.url` to create sitemap.xml](https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml#L3)

**Comment by GitHub-Mike** [comment]
OK, step 2: solution for `<lastmod>` Tag.

I  added "jekyll-last-modified-at" in Gemfile and run `bundle install`. Then added option - jekyll-last-modified-at  in _config.yml:

> gems:
  `- jekyll-sitemap`
  `- jekyll-last-modified-at`

result:

> `<lastmod>2016-05-09T17:10:07+02:00</lastmod>`

I need a solution for `<changefreq>` Tag only. :-)

Mike

**Comment by pathawks** [comment]
Thanks @xHN35RQ :+1:

Yes, setting `site.url` is the right way.
