### ISSUE TITLE
Multiple slashes in the sitemap URLs

### ISSUE THREAD

**Issue by ionutvelicu** [jekyll/jekyll-sitemap#117]
Hello!

I saw in the issues history that issues related to my problem were discussed in the past. However, I am not able to have a correct result with my current configuration:

```
url: 'http://www.example.com'
baseurl: /
permalink: /:title
```

This is the configuration _inherited_ from the theme I am using. If I remove the **permalink** slash, I end up with messed up post links in various parts of the website. If I remove the **baseurl** slash, styles and scripts are messed up on pages such as _http://www.example.com/tag/test_.

Since I am tied to this current config, would you consider having some validation to avoid multiple slashes, or would you expect these kind of issues to be resolved at the theme level?

Thanks!

**Comment by benbalter** [comment]
@ionutvelicu see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/ and http://ben.balter.com/jekyll-style-guide/config/#baseurl. The `baseurl` flag should never be `/`.

**Comment by ionutvelicu** [comment]
Thank you, @benbalter !
So it looks like this is a non-issue for the plugin itself. I'll fix it at the theme level.
Thanks much!
