### ISSUE TITLE
Can't seem to get sitemap.xml to be generated....

### ISSUE THREAD

**Issue by rwillett** [jekyll/jekyll-sitemap#118]
Hi,

We're having trouble getting sitemap.xml to be generated. We will admit up front we are NOT experts in Jekyll or Ruby and this may well be a novice mistake we are making. So apologies if we have missed something stupid and wasting peoples time.

We have setup a small Jekyll site which we believe works, we host it ourselves at 

https://www.jambuster.london

We update the site locally and we can send files up. As we are not experts in Jekyll or Ruby we are working by rote to make sure we do the right things. As we get to understand things more we will experiment more. 

We *believe* we have setup Jekyll correctly and installed jekyll-sitemap correctly. We have read the front page and the issues and have checked that jekyll-sitemap is at the end of the gems.

```
# Plugins
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

gems: ['jekyll_video_tag']

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
```

We have also checked that we don't even have a plugins directory so there is no old plugin sitemap generator lying around.

Our _config.yml does not contact 
```
safe: true
```

Each of our pages front matter has 
```
sitemap: true
```

When we build the site we do NOT get an errors. We build the site using 

```
clear && bundle exec jekyll serve
```

We have checked that jekyll-sitemap is installed 

```
Robs-MacBook-Pro:minimal-mistakes rwillett$ bundle show jekyll-sitemap
/Library/Ruby/Gems/2.0.0/gems/jekyll-sitemap-0.10.0
Robs-MacBook-Pro:minimal-mistakes rwillett$
```

We have now reached the end of our knowledge. We cannot see any sitemap.xml in the _site directory, yet we do seem to have the right files for uploading to our server.

Any suggestions welcomed please

Thanks

Rob

**Comment by benbalter** [comment]
Try changing:

```yml
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap

gems: ['jekyll_video_tag']
```

to 

```yml
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll_video_tag
```

I suspect the second `gem` flag is overriding the first.

**Comment by rwillett** [comment]
@benbalter 

Bingo. We now have a sitemap.xml.

We have learnt a little more about Jekyll. Long way to go though :)

Thank you for the very prompt and helpful reply.

Best wishes.
