### ISSUE TITLE
`loc` set properly for Google Analytics?

### ISSUE THREAD

**Issue by jgoodall** [jekyll/jekyll-sitemap#120]
After installing the plugin, Google Analytics complains about my sitemap: `This is not a valid URL. Please correct it and resubmit.`. I believe it may be because the value of `loc` does not include the protocol (such as http). All of the examples in the Google docs seem to include them (e.g. https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190).

Would it be possible to generate the sitemap with the full URL?

**Comment by pathawks** [comment]
What is the value of `url` in your `_config.yml`?

That is probably where you should be setting the protocol. Maybe there is something we could do better on our end to check this and maybe raise a warning.

As an aside, I understand why Jekyll lacks any core function to return a full validated absoulte URL, but it sure would be useful!

**Comment by jgoodall** [comment]
Yes, that solved the problem google was complaining about. Thank you for the suggestion. Maybe the fact that the `url` is used by the plugin to build the sitemap should be in the documentation?
