### ISSUE TITLE
sitemap.xml in _site not pushed because _site/ in .gitignore

### ISSUE THREAD

**Issue by BenU** [jekyll/jekyll-sitemap#122]
Thank you for making this gem!  I added it to my gemfile, bundle installed, updated _config.yml and now have a sitemap.xml file in my _site/ directory.  My issue/confusion is around the fact that since `_site/` is in my .gitignore file, the sitemap never gets uploaded to my github repository and is never part of my site. 

Am I doing something wrong?  Any thoughts?

**Comment by benbalter** [comment]
@BenU :wave: Can you post a link to your site, if it's public? The plugin should run on GitHub Pages when your site is built, meaning the resulting file will be in the served site.

**Comment by BenU** [comment]
Hi Ben,

Thanks for your note.  The site is public and is at benu.github.io with custom domain, https://benjaminunger.com

Best,
Ben

**Comment by kleinfreund** [comment]
@BenU Have a look, the file is there: https://benjaminunger.com/sitemap.xml

**Comment by BenU** [comment]
Ah!  Thanks.  Have a lot to learn about Jekyll, Jekyll-sitemap, SEO, etc. very grateful. 

Best,
Ben
