### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by tgragnato** [jekyll/jekyll-sitemap#126]
Switching from this plugin to a liquid-based sitemap.xml increased build performance.
Previously the whole process took about **70-60s**, after the change 19-13s...

```xml
---
layout: null
---
<?xml version='1.0' encoding='UTF-8'?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

  <url>
    <loc>{{ "/index.html" | prepend: site.baseurl | prepend: site.url }}</loc>
    <priority>1.0</priority>
  </url>

  {% for page in site.pages %}
  <url>
    <loc>{{ page.url | prepend: site.baseurl | prepend: site.url }}</loc>
    {% if page.updated_at %}<lastmod>{{ page.updated_at | date_to_xmlschema }}</lastmod>{% endif %}
    <priority>0.7</priority>
  </url>
  {% endfor %}

  {% for post in page.posts %}
  <url>
    <loc>{{ post.url | prepend: site.baseurl | prepend: site.url }}</loc>
    {% if page.updated_at %}<lastmod>{{ post.updated_at | date_to_xmlschema }}</lastmod>{% endif %}
    <priority>0.3</priority>
  </url>
  {% endfor %}

</urlset>
```

Suggestion: this is something substantial, it should be reported somewhere in the doc.

**Comment by pathawks** [comment]
I'm not really sure what to make of this. Your sitemap has fewer features than this plugin currently has, and I don't think we should be sacraficing any features for a small performance gain.

If there were something we could do to speed up generation of the sitemap while keeping our current feature set, _that_ is something I would be open to.

**Comment by tgragnato** [comment]
I have not looked at the implementation of the plugin, sorry.
I am aware of the differences in features.
I just thought it would be useful to report the thing ;)
Just in case someone needs.
It's up to you what to make, I guess.
