### ISSUE TITLE
Jekyll serve remove a draft after I edit it.

### ISSUE THREAD

**Issue by oncleben31** [jekyll/jekyll-sitemap#130]
Issue previously posted in https://github.com/jekyll/jekyll/issues/5446
It seems related to jekyll-sitemap so @pathawks asks me to post it here.

## My Reproduction Steps

From a Jekyll site with minima:
*   I create a draft named test.markdown in `_drafts`folder
```markdown
---
layout: post
title:  "test"
---
test3
````
*   I launch the local server with the command 'bundle exec jekyll serve --config _config.yml,_config.dev.yml --host 0.0.0.0 --force_polling --drafts -V``
*   I check with chrome the draft is accessible.
*   When I edit the draft and save it, I see the local server detect a change and relaunch the build but the draft is deleted from the _site folder.

Syou can see my repo and configuration on [oncleben31.github.io](https://github.com/oncleben31/oncleben31.github.io)

## The Output I Wanted

The draft should be accessible after a refresh triggered by Jekyll serve

**Comment by artlogic** [comment]
I've submitted pull request #131 that fixes this.

**Comment by artlogic** [comment]
With the PR merged, I think this can be closed. Are you able to test with the latest version and confirm, @oncleben31?

**Comment by oncleben31** [comment]
@artlogic I confirm problem solved with jekyll-sitemap v0.12.0
