### ISSUE TITLE
Drop issues section from Readme

### ISSUE THREAD

**Issue by zdroid** [jekyll/jekyll-sitemap#134]
It'd be a pretty good to move issues section out of readme and put the listed issues in projects.

Thoughts?

**Comment by pathawks** [comment]
Can you elaborate a bit? I'm not sure I understand.

The issues listed in the Readme are not exactly things we can fix, but we do need to let users know about them.

**Comment by zdroid** [comment]
Oh, I get it now. It's a bit confusing, though. Maybe you should rename the section to "Known Issues" so users know what's actually meant there? :wink:

**Comment by pathawks** [comment]
Good idea :+1:
Mind submitting a PR?

I wonder if we could add an “Unknown Issues” section 😝jk
