### ISSUE TITLE
Use Travis to cut new Gems

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-sitemap#148]
Today I learned that Travis [can be configured](https://docs.travis-ci.com/user/deployment/rubygems/) to release a new Gem when a new tag is added to a repository.

Can we set this up for Jekyll Plugins? I don't mind doing the leg work of configuring everything.

/cc: @jekyll/ecosystem

**Comment by envygeeks** [comment]
I could never get it to work right.

**Comment by pathawks** [comment]
I'd like to try this.

226fe9bb7d202b2992e95c81d220ba69b72ea98a
