### ISSUE TITLE
How to have the priority tag in my sitemap.xml

### ISSUE THREAD

**Issue by etiennedesign** [jekyll/jekyll-sitemap#152]
Hi, 
i would like to have the priority tags in my sitemap.xml.
Is there a way to generate them with the plugin? Maybe using the YAML front matter ?

Thanks!

**Comment by parkr** [comment]
Prior art: we removed `priority` in #33.

**Comment by etiennedesign** [comment]
Ok so priority tags are not really necessary for seo.
Thanks for the fast reply.

**Comment by parkr** [comment]
@etiennedesign Generally speaking, no it's not really necessary. That said, some people need it. We removed it in #33 because it just defaulted to `normal` and was not useful. We decided most users wouldn't need any priority tweaking and nixed it.
