### ISSUE TITLE
Ampersands in URL not being escaped in generated sitemap.xml

### ISSUE THREAD

**Issue by agmathew** [jekyll/jekyll-sitemap#158]
I'm using v1.0.0 of jekyll-sitemap and am finding that the generated sitemap.xml is not properly escaping ampersands. For example, URLs like this: 

`http://localhost:4000/q-&-a-session/`

are resulting in lines like this in the sitemap.xml, which is invalid XML:

`<loc>http://localhost:4000/q-&-a-session/</loc>`

instead of the following correct XML:

`<loc>http://localhost:4000/q-%26-a-session/</loc>`

**Comment by pathawks** [comment]
Looks like we should `xml_escape` all URLs.
