### ISSUE TITLE
Jekyll deprecation warning on `gems` key in config`

### ISSUE THREAD

**Issue by tejasbubane** [jekyll/jekyll-sitemap#181]
Jekyll changed the `gems` key in `_config.yml` to `plugins` in `v3.5.0`: https://jekyllrb.com/news/2017/06/15/jekyll-3-5-0-released/

Readme suggests to add this plugin to `gems` section. Although that is just a deprecation warning and it is backwards compatible and still works, I think we should mention about this warning in the readme.

**Comment by pathawks** [comment]
Good call.

We should wait until GitHub Pages is using `v3.5.0`, but then I agree that we should mention this :+1:

**Comment by tejasbubane** [comment]
Now that github pages uses `v3.5+`: https://pages.github.com/versions/, we can make this change.
