### ISSUE TITLE
Sitemap url which jekyll-sitemap generates seems a bit wrong?

### ISSUE THREAD

**Issue by gipcompany** [jekyll/jekyll-sitemap#182]
After applying jekyll-sitemap, my website https://gipcompany.github.io/robots.txt gives the following contents.

`Sitemap: https://gipcompany.github.io//sitemap.xml`

As you can see, there are double `/`s and I think it's duplicated, but is it done intensionally? The correct one is like below?

`Sitemap: https://gipcompany.github.io/sitemap.xml`

**Comment by benbalter** [comment]
@gipcompany I suspect you may have set your baseurl as `/`. See http://ben.balter.com/jekyll-style-guide/config/#baseurl.

**Comment by 7php** [comment]
yes I also believe it the baseurl. 
@gipcompany to verify this, try to analyse urls on your page and a post page. If you see double slashes, it's definitely the baseurl.

**Comment by gipcompany** [comment]
Thank you!

I checked around the setting `url`. The trick was the value of `url`.

Below fix this problem.

```
diff --git a/_config.yml b/_config.yml
index 6f2cb6e..ee3dfd1 100644
--- a/_config.yml
+++ b/_config.yml
@@ -20,7 +20,7 @@ description: > # this means to ignore newlines until "baseurl:"
   Hi, I'm Ham living in Chiba (Japan). I'm a Ruby programmer.
   I post blogs discussing web programming (Ruby, Rails, JavaScript, Linux, Advertisement, etc.), English, and my personal opinions.
 baseurl: "" # the subpath of your site, e.g. /blog
-url: "https://gipcompany.github.io/"
+url: https://gipcompany.github.io
 twitter_username: hamjuku
 github_username:  gipcompany
```
