### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by michaellautman** [jekyll/jekyll-sitemap#190]
I'm running jekyll locally to build a site that will be hosted.  When I build the sitemap all of the URLs are http://localhost.  How do I configure the plugin to generate the sitemap with the correct URL for the site?

**Comment by DirtyF** [comment]
1. Set your production url in `_config.yml` e.g. `url: http://mydomain.com`
2. Run Jekyll in production environment `JEKYLL_ENV=production bundle exec jekyll build` to override development settings.

**Comment by michaellautman** [comment]
Thank you.

**Comment by pathawks** [comment]
Where is this documented?

**Comment by DirtyF** [comment]
@pathawks Do you want me to add this use case in the README?

**Comment by michaellautman** [comment]
I think it would be very helpful if this were in the readme.md file.

Sent from Astro for iOS


On Sep 27, 2017 at 12:33 PM, Frank Taillandier <notifications@github.com>
wrote:


@pathawks <https://github.com/pathawks> Do you want me to add this use case
in the README?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/jekyll/jekyll-sitemap/issues/190#issuecomment-332580361>,
or mute the thread
