### ISSUE TITLE
exclude directories via config

### ISSUE THREAD

**Issue by COV-GIS** [jekyll/jekyll-sitemap#192]
Being able to exclude entire directories from being included in the sitemap would be a nice enhancement.

**Comment by benbalter** [comment]
We should document it better, but I believe you should be able to do this via front matter defaults. See

https://github.com/jekyll/jekyll-sitemap#exclusions

and 

https://jekyllrb.com/docs/configuration/#front-matter-defaults

**Comment by COV-GIS** [comment]
Thanks for reply.

I was unaware of the front matter defaults. Will be very handy in general.

That's not a viable solution however. The directory I'm trying exclude contains prebuilt apps (including a lot of html snippets for widgets) and other content that I don't want included in sitemap. Jekyll's roll is simply to copy that directory as is to `_site`. There's nothing there to be processed.

It's a more of an issue with my workflow. Needs to be excluded from Jekyll and copied with the task runner.

Thanks again!

**Comment by benbalter** [comment]
I believe you should be able to set a front matter default for the parent directory, and all subdirectories would be excluded.
