### ISSUE TITLE
Configuration options – are they planned?

### ISSUE THREAD

**Issue by alekseyg** [jekyll/jekyll-sitemap#20]
Are any config options planned for this gem? I'm making a fork and adding some that I need. I wanted to know if something is already in the works or not and what the API should look like for the options.

**Comment by pathawks** [comment]
> Are any config options planned for this gem?

@benbalter [on #21](https://github.com/jekyll/jekyll-sitemap/pull/21#issuecomment-45121451):
> I'm generally skeptical about adding more configuration options to what should be a set-it-and-forget it plugin.

@parkr [on #60](https://github.com/jekyll/jekyll-sitemap/issues/60#issuecomment-66708671):
> the :christmas_tree: of configuration options is not a :christmas_tree: we want to grow, so we were trying to decide on sane defaults instead.

**Comment by pathawks** [comment]
What action needs to happen next for this issue?

**Comment by alekseyg** [comment]
I'm guessing we're not adding options, so it should to be closed. Instead we removed the defaults that don't belong: #33, #34, and #35.
