### ISSUE TITLE
url is still localhost

### ISSUE THREAD

**Issue by ScriptWorld-git** [jekyll/jekyll-sitemap#211]
I got my custom url in _config.yml in line url: http://example.com

but my sitemap is still using "localhost:4000"...
im not using GitHub pages, I host the server on my own linux server, but this shouldn't be a problem, right ?

**Comment by DirtyF** [comment]
What are you trying to do?
How is this related to jekyll-sitemap?

**Comment by ScriptWorld-git** [comment]
jekyll sitemap is creating the `sitemap.xml` file in _site folder, right ?
i host my jekyll blog on the domain `https://example.com`` and already specified that in the `_config.yml` on the `url:` tag.
when i serve the website with `bundle exec jekyll serve` , the sitemap will be created, but all the links inside the file are not with my custom url but with the `localhost:4000` url. they need to be replaced with the url inside the _config.yml

sorry maybe my fist question was a little bit unclear. Hope you can help me.

**Comment by simonhaenisch** [comment]
If you serve your site with `jekyll serve`, then url will internally be overwritten for dev purposes... you can find that info somewhere in the docs. You need to use `jekyll build` and set your server up to serve the `_site` folder.

**Comment by ScriptWorld-git** [comment]
thank you very much ! for now I hosted the the server with serve and proxied my nginx to localhost ... I will do a proper setup now.

**Comment by simonhaenisch** [comment]
`jekyll serve` is meant for development only, not sure what other security related issues you could run into with that... you should rather run a file watcher or git hook to re-run `jekyll build` programmatically when your files/repository change.
