### ISSUE TITLE
jekyll-sitemap in container

### ISSUE THREAD

**Issue by davidobrien1985** [jekyll/jekyll-sitemap#216]
Hi,

I'm hosting my jekyll site inside of a container and this doesn't seem to work well with the `jekyll-sitemap` plugin.

```
<urlset xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"><url><loc>http://0.0.0.0:4000/blog/</loc></url><url><loc>http://0.0.0.0:4000/contact/</loc></url><url><loc>http://0.0.0.0:4000/</loc></url></urlset>
```

Does this plugin not like creating a sitemap in a container?
I would've expected it to use the `site.url` value, not the `http://0.0.0.0` value.

**Comment by pathawks** [comment]
Duplicate of #215
