### ISSUE TITLE
 Limit sitemap result by URL

### ISSUE THREAD

**Issue by ediano** [jekyll/jekyll-sitemap#218]
Sorry, I'm using Google Translator to translate this content.

How can I display a maximum amount of url in a sitemap through the url of the site.

Look, let's assume I have 500 url in a sitemap, but I want to split it in two this way.

/sitema.xml?redirect=false&start-index=1&max-results=250
/sitema.xml?redirect=false&start-index=251&max-results=500

It is possible?

**Comment by pathawks** [comment]
This is not possible, and will never be possible since Jekyll is a *static* site generator–meaning there is no server side processing of content.

**Comment by ediano** [comment]
Thank you very much for your attention.

Your response was very helpful.
