### ISSUE TITLE
Feature request: include URLs not managed by Jekyll

### ISSUE THREAD

**Issue by rayshan** [jekyll/jekyll-sitemap#226]
Hi!

Use case: I have a website generated by Jekyll and GitHub Pages:
https://shan.io/
https://github.com/rayshan/rayshan.github.io

I also have project pages hosted by GitHub Pages on the same domain, for example:
https://shan.io/startup-equity-calculator/
https://github.com/rayshan/startup-equity-calculator

May I have the ability to manually add project pages not generated by Jekyll to [`sitemap.xml`](https://shan.io/sitemap.xml)? Maybe somewhere in `_config.yml`. Thanks!

**Comment by pathawks** [comment]
Unfortunately no, this feature is beyond the scope of this plugin.

What you _could_ do is copy our [`sitemap.xml` template](https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml) to your site, and then add anything else you need there. :+1:

**Comment by rayshan** [comment]
Interesting, this could work, I'll give it a try. Alternatively I could hand-roll another sitemap file.
