### ISSUE TITLE
Issue in Robots.txt

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [jekyll/jekyll-sitemap#237]
In google search console it says "You have a robots.txt file that we are currently unable to fetch. In such cases we stop crawling your site until we get hold of a robots.txt, or fall back to the last known good robots.txt file."

I tried to add the new robots.txt file in root but not the success. Can Anyone help me?

**Comment by DirtyF** [comment]
👋 @rahulkumarsingh73690 
This repository issues are dedicated to documented bugs only.

Please head over to [our forum ](https://talk.jekyllrb.com) to ask for help on Jekyll's usage.
