### ISSUE TITLE
How to add pages to the sitemap that don’t exist

### ISSUE THREAD

**Issue by thomasedwards** [jekyll/jekyll-sitemap#249]
We have some pages that are delivered by proxy, so do not exist in Jekyll.

We have an API that provides the pages, and we have a plugin that can get this data.

Is there a way to add data to the sitemap, but for pages that don’t render in Jekyll?

**Comment by DirtyF** [comment]
You can always build your own sitemap.xml layout and gather data from you API with your plugin. This plugin won't solve that very specific use case.

**Comment by thomasedwards** [comment]
Ah perfect, of course! Thanks for the reply.
