### ISSUE TITLE
Question about <lastmod>

### ISSUE THREAD

**Issue by zhandosweb** [jekyll/jekyll-sitemap#259]
Hello!

Please, let me ask one question. 

In documentation written, that the **\<lastmod>** based on the date of the file changes in a filesystem. 

It means, that **\<lastmod>** is always dynamically? If I edit some post, then upload changes to hosting, **\<lastmod>** date will change automatically? 

I use **jekyll-last-modified-at** plugin too.

Sorry for the bad English, I'm still learning. I believe, that you understand me. And thank you for your work!

**Comment by zhandosweb** [comment]
> Hello!
> 
> Please, let me ask one question.
> 
> In documentation written, that the based on the date of the file changes in a filesystem.
> 
> It means, that is always dynamically? If I edit some post, then upload changes to hosting, date will change automatically?
> 
> I use **jekyll-last-modified-at** plugin too.
> 
> Sorry for the bad English, I'm still learning. I believe, that you understand me. And thank you for your work!

**Comment by ashmaroli** [comment]
`<lastmod>` is rendered based on the value reported by `jekyll-last-modified-at`.
So if the plugin outputs a different timestamp, the sitemap will be updated accordingly.

**Comment by emma-sax4** [comment]
I have two PDF resources on my site, and they never change at all. But whenever my sitemap generates (such as part of a Travis CI cron job), even if there were no changes to any documents or pages on the site, the sitemap will change the `<lastmod>` date/time of those two resources, and just those two resources.

![image](https://user-images.githubusercontent.com/7562793/73575953-e3478e00-443e-11ea-8b9b-726cb4451b73.png)

That above commit would lead to this: https://github.com/emma-sax4/emma-sax4.github.io/commit/4e4e763c232c1fdd32915b4c99966f50b6f2bda7.

Can anybody help me figure out why that is changing?
