### ISSUE TITLE
/sitemap vs xml

### ISSUE THREAD

**Issue by cauerego** [jekyll/jekyll-sitemap#261]
really sorry for the stupid question, but is this plugin also generating /sitemap ?

**Comment by ashmaroli** [comment]
If you're referring to the repo at https://github.com/ahoxus/ahoxus.github.io, I see a file named `sitemap.md` with a permalink attribute set to `/sitemap/`.

This could be the HTML page you're seeing..

**Comment by cauerego** [comment]
sorry! 😵😔

now i feel stupid! 🤣
