### ISSUE TITLE
front matter doesn't remove page from html

### ISSUE THREAD

**Issue by cauerego** [jekyll/jekyll-sitemap#262]
if #261 is true, then how can we remove pages from the /sitemap ?

both `sitemap: false` configurations global or per page don't work, although they do remove the page from the XML.

**Comment by ashmaroli** [comment]
Do you have a `permalink` setting in your config file? If yes, what is it?
Or better, please post the entire contents of your config file, here.

**Comment by cauerego** [comment]
thanks for the engagement!

got no such setting there. https://github.com/ahoxus/ahoxus.github.io/commits/master

**Comment by cauerego** [comment]
lol, closed by #261
