### ISSUE TITLE
Jekyll-sitemap dependency error

### ISSUE THREAD

**Issue by sebawrite** [jekyll/jekyll-sitemap#278]
**The Error Message**
`Dependency Error: Yikes! It looks like you don’t have jekyll-sitemap or one of its dependencies installed. In order to use Jekyll as currently configured, you’ll need to install this gem. If you’ve run Jekyll with bundle exec, ensure that you have included the jekyll-sitemap gem in your Gemfile as well. The full error message from Ruby is: ‘cannot load such file – jekyll-sitemap’ If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!`

**What I tried**
1. I’ve read through other people’s posts, but I haven’t found a way to solve this problem. At one point, I had to go through and uncomment plug-ins in my _config.yml file one by one and I was suprised to see that the following plugins produced a similar error (the amount of them. This is before I nuked my project and made a new one.)
2. Followed instructions to install, alter Gemfile, and alter _config.yml
3. Nuked the project, made a new one, and tried again.

**Comment by ashmaroli** [comment]
Simply altering your Gemfile won't do. You need to have the listed gems installed.
- Ensure you have `jekyll-sitemap` listed in your Gemfile and installed in your system / local project directory.
- Run `bundle install` to install any missing dependencies.
- Run Jekyll commands by prepending `bundle exec`. For example, `bundle exec jekyll build`
