### ISSUE TITLE
Sitemap having errors on Google Search console

### ISSUE THREAD

**Issue by build3r** [jekyll/jekyll-sitemap#287]
I have followed the instruction and added sitemap plugin in both gem file and in _config.xml. But the when I add my sitemap to Google Search console I get error  
`Sitemap can be read, but has errors` Invalid URL  
I using github pages and have set URL in _config.yml and my sitemap looks valid and the URLs are also absolute
[https://build3r.github.io/sitemap.xml](https://build3r.github.io/sitemap.xml)  

![image](https://user-images.githubusercontent.com/6481548/128325821-75f2538d-78f4-42d2-8e1e-678889001af5.png)

**Comment by gustavekenedi** [comment]
I'm having the same issue unfortunately. Have you found a solution?

**Comment by build3r** [comment]
@gustavekenedi looked like at error was an old one. After fixing the Google was not fetching the new one.
The way I fixed it is by changing the sitemap.xml path. Which made google to fetch is again and validate.
