### ISSUE TITLE
"index.html" is removed from URL when it shouldn't be

### ISSUE THREAD

**Issue by rubenwardy** [jekyll/jekyll-sitemap#67]
For example, `book_index.html` -> `book_`

https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml#L16

**Comment by parkr** [comment]
That should probably be `replace:"/index.html","/"` /cc @pathawks

**Comment by rubenwardy** [comment]
I thought that might be the case. Would the index.html in the root directory be `/index.html` or `index.html`?

**Comment by parkr** [comment]
We'll add a test for that case. In theory, all paths should start with a forward slash.
