### ISSUE TITLE
Update dependency for Jekyll 3

### ISSUE THREAD

**Issue by gjtorikian** [jekyll/jekyll-sitemap#74]
https://github.com/jekyll/jekyll-sitemap/blob/master/jekyll-sitemap.gemspec#L17

**Comment by parkr** [comment]
I was thinking we might actually rewrite this as a hook for Jekyll 3! Thoughts? It'd be a `post_render` hook for `Jekyll::Site`. /cc https://github.com/jekyll/jekyll/pull/3553

**Comment by pathawks** [comment]
I have been using Jekyll-Sitemap with Jekyll 3 without issue.

```gemfile
source 'https://rubygems.org'

gem 'jekyll', :github => 'jekyll/jekyll', :branch => 'master'
gem 'kramdown'
gem 'pygments.rb'

group :jekyll_plugins do
	gem 'jekyll-sitemap', :github => 'jekyll/jekyll-sitemap', :branch => 'master'
end
```

```text
Gems included by the bundle:
...
  * jekyll (3.0.0.pre.beta2 ae584e4)
  * jekyll-sitemap (0.8.1 4b3436f)
...
```

So, that's weird. :confused:

**Comment by parkr** [comment]
Jekyll `~> 2.0` is a development dependency – @gjtorikian did `bundle install` give you errors?

**Comment by gjtorikian** [comment]
It did indeed.

I have no thoughts on Jekyll hooks because I haven't been following the plan for them. So go with your heart!

**Comment by parkr** [comment]
> It did indeed.

Weird – bundler should allow you to install things regardless of the development dependencies. Maybe it was jemoji that gave you the trouble?

**Comment by pathawks** [comment]
Is there any action that needs to be taken here?

**Comment by gjtorikian** [comment]
guess not
