### ISSUE TITLE
sitemap.xml URL's generating incorrectly with '//' in path

### ISSUE THREAD

**Issue by jonbartlett** [jekyll/jekyll-sitemap#76]
I have read the closed issues relating to ```url``` and ```baseurl``` in ```_config.yml``` and suspect this is related however can't find a solution.

In ```_config.yml``` I have:
```
url:              http://www.jonbartlett.org
baseurl:          '/'
```

When the [sitemap.xml](http://www.jonbartlett.org/sitemap.xml) is generated the urls are generated with a double slash in the path:

```
<url>
<loc>http://www.jonbartlett.org//</loc>
</url>
<url>
<loc>http://www.jonbartlett.org//notes/</loc>
</url>
</urlset>
```

When I set ```baseurl``` to null the sitemap.xml is generated correctly. However the template I am using [Poole](https://github.com/poole/hyde) needs ```baseurl:    '/'``` as this is used to reference the root/home.

Now I could change the template. But just to confirm that there is a dependency on ```baseurl``` being null when running from the root of a custom domain?

**Comment by kleinfreund** [comment]
There should not be a dependency on `baseurl` inside Jekyll at all. Correct me if I'm wrong, but when you do `{{ site.url }}{{ site.baseurl }}` or `{{ site.url }}{{ site.baseurl }}notes/` this __does not__ happen?

**Comment by pathawks** [comment]
> Now I could change the template. But just to confirm that there is a dependency on baseurl being null when running from the root of a custom domain?

Yes, that is correct.

**Comment by jonbartlett** [comment]
The more I look into this, the more I see that this issue obviously relates the Poole/Hyde template. It should not be setting ```baseurl '/'```. The Poole/Lanyard template does not do this as do most other Jekyll sites.

I have amended my site and raised a [PR](https://github.com/poole/hyde/pull/93) to fix the issue.

Thanks for the replies.
