### ISSUE TITLE
Allow for the inclusion of static files (e.g. static files in assets dir)

### ISSUE THREAD

**Issue by iiegn** [jekyll/jekyll-sitemap#77]
include files with specific extensions e.g. *.pdf or *.tgz into the sitemap (maybe only from within the assets dir).

at the moment, only *.html files are treated 'special' and are included.

**Comment by sondr3** [comment]
Not sure if this is something that should even be in a sitemap, a sitemap is a way to list all the content pages on your website, not documents and such.

**Comment by iiegn** [comment]
i was considering this, and tried to find a definitive answer - but i couldn't. so, a pragmatic approach:
 - the sitemap protocol doesn't forbid it
 - [google's site map file](http://www.google.com/sitemap.xml) lists pdfs

and then there is
 - http://webmasters.stackexchange.com/questions/58789/what-is-the-correct-format-and-attributes-for-adding-a-pdf-to-an-xml-sitemap

i'm not saying all this *is* a definitive answer but it gave me reasons to believe the issue might be valid.

**Comment by benbalter** [comment]
I believe any file with YAML front matter, even if empty, will be included, so really, it's a question of including binary files, which absent a strong case to the contrary, am not sure that it's core to what the plugin should do (and would likely require a potentially confusing configuration flag).

**Comment by iiegn** [comment]
site.posts, site.collections, and site.html_pages are considered for inclusions (check ``sitemap: false``) - and then 'all non-jekyll site files with an HTML extension.'

* now, the question is should /only/ ``.html`` pages be included?

at least, Google is also processing [information about video and image content](https://support.google.com/webmasters/answer/156184?hl=en) (but that's a different issue).

for myself, the issue is the inclusion of ``.pdf`` files but i see, once they get included it would make sense to include all indexable files (the ones from (Google)[https://support.google.com/webmasters/answer/35287?hl=en]; (Bing)[https://blogs.bing.com/webmaster/2012/10/19/advanced-query-operators-filetype-ext-understanding-the-differences/] knows about ``filetype:`` but it is not clear what the whole set is.)

**Comment by dtharris** [comment]
I would also find indexing of PDF files very helpful. Google Scholar links back to self-archived papers for easy download, so indexing PDFs would be very helpful for academics. 

Even a feature to indicate directories of files that should be indexed would be useful as @iiegn suggests.

**Comment by kevinoid** [comment]
+1 for adding a way to include additional files in the sitemap.

Personally, I'm interested in including `.xhtml` files in addition to `.html`.  Is there any chance you would consider allowing a configuration option to specify extensions (or include/exclude patterns) that the user wants to be included in the sitemap?

**Comment by pathawks** [comment]
I think including `.xhtml` files is a separate issue from the inclusion of binary files (like PDF)

I have added this in #93

**Comment by iloveip** [comment]
Yes, I would like to index PDF files too. Is there any update on this?

**Comment by rowe-morehouse** [comment]
.pdf files should definitely be able to be included in sitemaps. 

If you don't want to try to index binaries, then how about a feature to force add an URL to the sitemap, configurable in the .yml ??

Is this possible now? Thank you.

**Comment by iiegn** [comment]
concerning the inclusion of .pdf files, i believe, the discussion on the [pull request](../pull/97) page is going into this direction.
however, i don't quite understand the second point - is it supposed to mean that, for example, to add 20 pdf files 20 individual lines would have to be added to a file? for me then, having a pattern to dynamically include files (and take care of changing number of files and changing file names) is more convincing.

**Comment by rowe-morehouse** [comment]
Hi @iiegn, thanks for your response. Yes, a pattern to allow inclusion of addition URIs in the sitemap, no matter if the new feature in PR supports the file type or not. For example, in the `_config.yml` something like:

`sitemap-force-include:`
`  - "/images/image1.png"`
`  - "/docs/document.ppt"`
 ` - "docs/*.txt"

etc.

**Comment by iiegn** [comment]
ah, so the pattern could be some ruby-pattern-for-filename-matching-thing, and ``*.pdf `` (now, back with the ``*.``) would be a possible value. it's more general than what #97 is about; would look (almost) similar in the general and always-used-as-an-example-pdf case but could cover some more cases. appealing.
however, [the general problem](../pull/97#issuecomment-194359440) still stands.

**Comment by pathawks** [comment]
I am not a fan of the idea of adding a config option and forcing the user to decide what should or should not be added to the sitemap, especially if it means that everybody just adds the same `sitemap-include: *.pdf` option.

What about just including _all_ file extensions that major search engines index. [Google has a list of filetypes they index](https://support.google.com/webmasters/answer/35287?hl=en). Is there any disadvantage aside from perhaps a larger sitemap?

**Comment by pathawks** [comment]
I have added PDF files to the sitemap in #109

Let us consider future additions on a case by case basis, instead of leaving it to the user to figure it out.

**Comment by iloveip** [comment]
Hi @pathawks,

Thank you very much for the update. How can I uprage the gem to use this feature?

**Comment by pathawks** [comment]
Until a new :gem: is released, you can add this to your Gemfile:

```ruby
gem 'jekyll-sitemap', :github => 'jekyll/jekyll-sitemap', :branch => 'master'
```

**Comment by iloveip** [comment]
@pathawks thank you very much!
