### ISSUE TITLE
Getting double forward slashes

### ISSUE THREAD

**Issue by csu** [jekyll/jekyll-sitemap#79]
I'm getting two forward slashes in all my URLs in my sitemap even though Jekyll generates permalinks properly everywhere else:

```
<url>
<loc>
http://christopher.su//2015/selenium-chromedriver-ubuntu/
</loc>
<lastmod>2015-05-29T00:00:00+00:00</lastmod>
</url>
<url>
```

**Comment by pathawks** [comment]
In your config, what are the values of `url` and `baseurl`?

Is your `baseurl` set to “`/`”?

**Comment by csu** [comment]
Yeah, is that incorrect? I'll try removing it.

**Comment by csu** [comment]
That fixed it. Thanks, @pathawks!
