### ISSUE TITLE
Allow for exclusion of custom directories

### ISSUE THREAD

**Issue by patrickt010** [jekyll/jekyll-sitemap#82]
Running into an issue where bower_components is being indexed. 

```
sitemap:
  exclude:
    - /bower_components
```

**Comment by benbalter** [comment]
Could you exclude the md files on a Jekyll level? the static files shouldn't be included, IIRC.

**Comment by patrickt010** [comment]
Some of the components I am using have html files included. So the sitemap is indexing them by default. I would prefer not to remove or modify those files. 

patrickthompson.com/sitemap.xml

```
<url>
<loc>
  https://patrickthompson.com/bower_components/viewerjs/ViewerJS/index.html
</loc>
  <lastmod>2015-08-18T18:56:54+00:00</lastmod>
</url>
<url>
<loc>
  https://patrickthompson.com/bower_components/wow/spec/javascripts/fixtures/custom.html
</loc>
  <lastmod>2015-08-18T18:56:54+00:00</lastmod>
</url>
<url>
<loc>
  https://patrickthompson.com/bower_components/wow/spec/javascripts/fixtures/simple.html
</loc>
  <lastmod>2015-08-18T18:56:54+00:00</lastmod>
</url>
<url>
<loc>
  https://patrickthompson.com/bower_components/wow/demo.html
</loc>
  <lastmod>2015-08-18T18:56:54+00:00</lastmod>
</url>
<url>
<loc>
  https://patrickthompson.com/bower_components/fancybox/demo/iframe.html
</loc>
  <lastmod>2015-08-18T18:56:54+00:00</lastmod>
</url>
<url>
<loc>
  https://patrickthompson.com/bower_components/fancybox/demo/index.html
</loc>
  <lastmod>2015-08-18T18:56:54+00:00</lastmod>
</url>
```

**Comment by pathawks** [comment]
It seems that the proper way to exclude these files would be using Jekyll's existing `defaults`:

```yaml
defaults:
  -
    scope:
      path: 'bower_components'
    values:
      sitemap: false
```

Unfortunately, it seems there is no way of applying these defaults to static files (files that lack front matter).

The sitemap template is [already capable](https://github.com/jekyll/jekyll-sitemap/blob/master/lib/sitemap.xml#L14) of excluding static files *if* `sitemap: false` is somehow set. I am just not sure how this *could* be set for static files.

**Comment by patrickt010** [comment]
Thanks for the suggestion I gave it a try, unfortunately as you mentioned this will not work for static files. A way to exclude files that lack front matter would be a great, but not sure how many other people have this problem.

**Comment by benbalter** [comment]
> as you mentioned this will not work for static files. 

I meant Jekyll's native exclude function. I assume you don't need the static HTML files from your bowered components published? (bonus: It'll also speed up your site). 

As an example, I have the following in my site's `_config.yml` file:

```yml
exclude:
  - assets/vendor/bootstrap-sass/stylesheets
  - assets/vendor/font-awesome/less
  - assets/vendor/font-awesome/scss
  - assets/vendor/font-awesome/src
  - assets/vendor/modernizr/feature-detects
  - assets/vendor/modernizr/media
  - assets/vendor/modernizr/test
  - assets/vendor/anchor-js/index.html
```

**Comment by patrickt010** [comment]
@benbalter Thanks so much, this worked perfect!!

**Comment by garethjohnsdesign** [comment]
Thanks for this, exactly the solution I was looking for
