### ISSUE TITLE
jekyll-sitemap.rb:28:in `extname': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by chrisanthropic** [jekyll/jekyll-sitemap#89]
After updating to Jekyll 3.0 I get the following error when trying to run `jekyll build` or `jekyll serve`:

```
jekyll-sitemap.rb:28:in `extname': no implicit conversion of nil into String (TypeError)
```

**Comment by parkr** [comment]
@chrisanthropic I don't believe this is a bug with the latest version – what version of jekyll-sitemap are you using?

```bash
bundle list
```
