### ISSUE TITLE
No support for scheme-agnostic base url

### ISSUE THREAD

**Issue by duetosymmetry** [jekyll/jekyll-sitemap#98]
Specifying `url: //domainname` works for generating a scheme-agnostic web site, one which is hosted at both `http://domainname` and `https://domainname`. However, the `sitemap.xml` which is generated by `jekyll-sitemap` will have URLs of the form `//domainname/etc` with no scheme.

Can we make `jekyll-sitemap` detect if the `site.url` starts with `//`, and if so, prepend `https:`?

**Comment by parkr** [comment]
Hey @duetosymmetry! I'm going to defer to Paul Irish on this one and say that [protocol-relative URL's are a Bad Idea :tm:](http://www.paulirish.com/2010/the-protocol-relative-url/). If the item is available via HTTPS, [then it should be requested using `https://`](https://twitter.com/paul_irish/status/588502455530311680?lang=en).

Thanks though!

**Comment by duetosymmetry** [comment]
Thanks for the response, @parkr. I just read the anti-pattern post and have come to see the light.

My problem was a bit of an XY problem. When I specified my `site.url` to start with `https://`, then Chrome and Firefox were unhappy loading cross-scheme resources (CSP problem?). The easiest solution for me so far has been to tell Apache to Rewrite requests from http to https, which also seems wrong, but less wrong than the other potential solutions.

**Comment by kleinfreund** [comment]
> The easiest solution for me so far has been to tell Apache to Rewrite requests from http to https, which also seems wrong

Why?

**Comment by duetosymmetry** [comment]
@kleinfreund why is this the easiest solution, or why does it seem wrong?

It seems wrong because it's just avoiding a problem that is there and not fixing the underlying cause. The underlying problem is as follows:
Load web page over HTTP -> resources are explicitly specified as HTTPS -> CSS has relative path to font file -> browser (Chrome or Firefox, not Safari) sees this as a violation of some default content security policy (CSP) because it is cross-scheme -> font resources fail to load.

**Comment by kleinfreund** [comment]
@duetosymmetry My bad, I thought the site itself was served as HTTPS, not only the font ressource.

**Comment by duetosymmetry** [comment]
@kleinfreund Everything is served over both HTTP and HTTPS. Loading the web page over HTTPS avoids the problem :)
